### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by mmuflih** [vectornguyen76/face-recognition#18]
Traceback (most recent call last):
  File "/home/muflih/Development/src/gitlab.com/face-recog-example/face-recognition/main.py", line 29, in <module>
    model = attempt_load("face_detection/yolov5_face/yolov5n-0.5.pt", map_location=device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muflih/Development/src/gitlab.com/face-recog-example/face-recognition/face_detection/yolov5_face/models/experimental.py", line 136, in attempt_load
    torch.load(w, map_location=map_location)["model"].float().fuse().eval()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muflih/Development/src/gitlab.com/face-recog-example/face-recognition/myenv/lib/python3.11/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muflih/Development/src/gitlab.com/face-recog-example/face-recognition/myenv/lib/python3.11/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muflih/Development/src/gitlab.com/face-recog-example/face-recognition/myenv/lib/python3.11/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'face_detection/yolov5_face/yolov5n-0.5.pt'

**Comment by mmuflih** [comment]
Fusing layers... 
/home/muflih/Development/src/gitlab.com/face-recog-example/face-recognition/myenv/lib/python3.11/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/home/muflih/Development/src/gitlab.com/face-recog-example/face-recognition/train.py", line 35, in <module>
    weight = torch.load("insightface/resnet100_backbone.pth", map_location = device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muflih/Development/src/gitlab.com/face-recog-example/face-recognition/myenv/lib/python3.11/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muflih/Development/src/gitlab.com/face-recog-example/face-recognition/myenv/lib/python3.11/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muflih/Development/src/gitlab.com/face-recog-example/face-recognition/myenv/lib/python3.11/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'insightface/resnet100_backbone.pth'

**Comment by vectornguyen76** [comment]
Download model in here:
https://drive.google.com/drive/folders/10UyYkdM-9vtT_HuwFToYzcJIV8jQD8NG?usp=sharing

**Comment by Ajay4615** [comment]
The above drive link showing the error..
